#ifndef IPINFO_H
#define IPINFO_H

#define IP_LOCALHOST "127.0.0.1"

#define IP_VMP 		 "192.168.21.2"
#define IP_CLIENT 	 IP_LOCALHOST

#define PORT_CTRL 	 5051
#define PORT_DATA 	 PORT_CTRL - 1

#define COMMAND_RESP_SIZE 	 64

#define PACKAGE_HEADER_SIZE 12
#define PACKAGE_DATA_SIZE	4096
#define FULL_PACKAGE_SIZE PACKAGE_HEADER_SIZE + PACKAGE_DATA_SIZE

#endif // IPINFO_H
