#ifndef IPINFO_H
#define IPINFO_H

#define IP_SERVER     "127.0.0.1"
#define IP_CLIENT     "127.0.0.1"

#define PORT_SERVER_COMMANDS    5000
#define PORT_SERVER_DATA        PORT_SERVER_COMMANDS + 1

#define PORT_CLIENT_COMMANDS    3000
#define PORT_CLIENT_DATA        PORT_CLIENT_COMMANDS + 1

#endif // IPINFO_H
